insert into board values (1,'test', false, null, 'title', 0, 'writer')
insert into board (title, content, writer, deleted, viewcnt, regdate) (select title, content, writer, deleted, viewcnt, regdate from board)
insert into board (title, content, writer, deleted, viewcnt, regdate) (select title, content, writer, deleted, viewcnt, regdate from board)
insert into board (title, content, writer, deleted, viewcnt, regdate) (select title, content, writer, deleted, viewcnt, regdate from board)
insert into board (title, content, writer, deleted, viewcnt, regdate) (select title, content, writer, deleted, viewcnt, regdate from board)
insert into board (title, content, writer, deleted, viewcnt, regdate) (select title, content, writer, deleted, viewcnt, regdate from board)
insert into board (title, content, writer, deleted, viewcnt, regdate) (select title, content, writer, deleted, viewcnt, regdate from board)
insert into board (title, content, writer, deleted, viewcnt, regdate) (select title, content, writer, deleted, viewcnt, regdate from board)
insert into board (title, content, writer, deleted, viewcnt, regdate) (select title, content, writer, deleted, viewcnt, regdate from board)
insert into board (title, content, writer, deleted, viewcnt, regdate) (select title, content, writer, deleted, viewcnt, regdate from board)
insert into board (title, content, writer, deleted, viewcnt, regdate) (select title, content, writer, deleted, viewcnt, regdate from board)
insert into board (title, content, writer, deleted, viewcnt, regdate) (select title, content, writer, deleted, viewcnt, regdate from board)
insert into board (title, content, writer, deleted, viewcnt, regdate) (select title, content, writer, deleted, viewcnt, regdate from board)
insert into board (title, content, writer, deleted, viewcnt, regdate) (select title, content, writer, deleted, viewcnt, regdate from board)
insert into board (title, content, writer, deleted, viewcnt, regdate) (select title, content, writer, deleted, viewcnt, regdate from board)